export const CREATE_HABIT = "CREATE_HABIT"
export const CREATE_HABIT_SAGA = "CREATE_HABIT_SAGA"

export const DELETE_HABIT = "DELETE_HABIT"
export const DELETE_HABIT_SAGA = "DELETE_HABIT_SAGA"

export const ERROR = "ERROR"

export const FETCH_HABIT_DETAILED_DATA = "FETCH_HABIT_DETAILED_DATA"
export const FETCH_HABIT_DETAILED_DATA_SAGA = "FETCH_HABIT_DETAILED_DATA_SAGA"

export const FETCH_HABIT_PREVIEW_DATA = "FETCH_HABIT_PREVIEW_DATA"
export const FETCH_HABIT_PREVIEW_DATA_SAGA = "FETCH_HABIT_PREVIEW_DATA_SAGA"

export const SET_TODAY_DONE = "SET_TODAY_DONE"
export const SET_TODAY_DONE_SAGA = "SET_TODAY_DONE_SAGA"

export const SET_TODAY_UNDONE = "SET_TODAY_UNDONE"
export const SET_TODAY_UNDONE_SAGA = "SET_TODAY_UNDONE_SAGA"

export const UPDATE_HABIT = "UPDATE_HABIT"
export const UPDATE_HABIT_SAGA = "UPDATE_HABIT_SAGA"
